// Game data: chapters, upgrades, cutscenes

export const CHAPTERS = [
  // HIGH SCHOOL
  {
    id: 'hs_practice_1',
    era: 'HIGH SCHOOL',
    name: 'First Day Drills',
    type: 'practice',
    icon: '🏃',
    description: 'Navigate cones & learn footwork',
    color: '#ef4444',
    teamColor: '#dc2626',
    uniform: 'hs',
    obstacleTypes: ['cone', 'defender_slow'],
    targetYards: 80,
    timeLimit: 30,
    lanes: 3,
    defenderCount: 3,
    difficulty: 0.6,
    starThresholds: [40, 65, 80],
    cutscene: {
      icon: '🏫',
      title: 'HIGH SCHOOL DEBUT',
      body: 'Coach Jenkins sees something special in you. Hit the practice field, freshman — time to prove you belong on the varsity squad!'
    },
    passText: 'Great practice! Coach is impressed.',
    failText: 'Needs more work. Hit the drills again.'
  },
  {
    id: 'hs_practice_2',
    era: 'HIGH SCHOOL',
    name: 'Speed Drills',
    type: 'practice',
    icon: '⚡',
    description: 'Beat the clock through the gauntlet',
    color: '#ef4444',
    teamColor: '#dc2626',
    uniform: 'hs',
    obstacleTypes: ['cone', 'cone', 'defender_slow'],
    targetYards: 100,
    timeLimit: 28,
    lanes: 3,
    defenderCount: 4,
    difficulty: 0.75,
    starThresholds: [60, 85, 100],
    cutscene: {
      icon: '⚡',
      title: 'SPEED DRILLS',
      body: "You're getting faster. Coach says your 40-time dropped a tenth of a second. Keep pushing!"
    },
    passText: 'Lightning fast! The scouts are watching.',
    failText: 'You can do better. Try again!'
  },
  {
    id: 'hs_game_1',
    era: 'HIGH SCHOOL',
    name: 'Homecoming Game',
    type: 'game',
    icon: '🏈',
    description: 'First varsity start — make it count!',
    color: '#ef4444',
    teamColor: '#dc2626',
    uniform: 'hs',
    obstacleTypes: ['defender_slow', 'defender_medium'],
    targetYards: 120,
    timeLimit: 35,
    lanes: 4,
    defenderCount: 5,
    difficulty: 0.85,
    starThresholds: [70, 100, 120],
    isBig: true,
    cutscene: {
      icon: '🏈',
      title: 'HOMECOMING FRIDAY NIGHT!',
      body: "Friday Night Lights! The whole town is watching. You get the ball on the first play — score a touchdown and you'll be a local legend!"
    },
    passText: 'TOUCHDOWN! The crowd goes wild! College scouts take notice.',
    failText: 'Tough game. Learn from it.'
  },
  {
    id: 'hs_game_2',
    era: 'HIGH SCHOOL',
    name: 'State Playoffs',
    type: 'game',
    icon: '🥇',
    description: 'Win the state championship',
    color: '#ef4444',
    teamColor: '#dc2626',
    uniform: 'hs',
    obstacleTypes: ['defender_slow', 'defender_medium', 'defender_fast'],
    targetYards: 150,
    timeLimit: 40,
    lanes: 4,
    defenderCount: 6,
    difficulty: 1.0,
    starThresholds: [90, 125, 150],
    isBig: true,
    cutscene: {
      icon: '🥇',
      title: 'STATE CHAMPIONSHIP!',
      body: "You've led the team to the state playoffs. One last game stands between you and a championship ring — and a full scholarship offer!"
    },
    passText: 'STATE CHAMPS! The scholarship offers are pouring in!',
    failText: 'So close. But a major college still wants you.'
  },
  // COLLEGE
  {
    id: 'col_practice_1',
    era: 'COLLEGE',
    name: 'College Camp',
    type: 'practice',
    icon: '🎓',
    description: 'Bigger, faster, stronger defenders',
    color: '#3b82f6',
    teamColor: '#1d4ed8',
    uniform: 'college',
    obstacleTypes: ['defender_medium', 'cone'],
    targetYards: 120,
    timeLimit: 30,
    lanes: 4,
    defenderCount: 5,
    difficulty: 1.1,
    starThresholds: [70, 100, 120],
    cutscene: {
      icon: '🎓',
      title: 'WELCOME TO COLLEGE!',
      body: 'These defenders are HUGE. Camp is intense — time to show you can compete at the next level. Your scholarship depends on it!'
    },
    passText: 'Solid camp! Your position on the depth chart is secured.',
    failText: 'Keep grinding. You'll earn more reps.'
  },
  {
    id: 'col_practice_2',
    era: 'COLLEGE',
    name: 'Film Study Drill',
    type: 'practice',
    icon: '📽️',
    description: 'Read the defense — find the gaps',
    color: '#3b82f6',
    teamColor: '#1d4ed8',
    uniform: 'college',
    obstacleTypes: ['defender_medium', 'defender_fast'],
    targetYards: 140,
    timeLimit: 32,
    lanes: 4,
    defenderCount: 6,
    difficulty: 1.2,
    starThresholds: [80, 115, 140],
    cutscene: {
      icon: '📽️',
      title: 'FILM STUDY',
      body: 'Coach shows you tape. You learn to read gaps, recognize blitzes, and exploit weaknesses. Now go apply it on the field!'
    },
    passText: 'Beautiful reads! You look like a veteran.',
    failText: "Back to the film room — but you're getting it."
  },
  {
    id: 'col_game_1',
    era: 'COLLEGE',
    name: 'Conference Opener',
    type: 'game',
    icon: '⚔️',
    description: 'First big conference matchup',
    color: '#3b82f6',
    teamColor: '#1d4ed8',
    uniform: 'college',
    obstacleTypes: ['defender_medium', 'defender_fast'],
    targetYards: 160,
    timeLimit: 38,
    lanes: 5,
    defenderCount: 7,
    difficulty: 1.3,
    starThresholds: [100, 135, 160],
    isBig: true,
    cutscene: {
      icon: '⚔️',
      title: 'CONFERENCE OPENER!',
      body: '80,000 fans. ESPN cameras. A top-15 ranked opponent. This is what you came to college for — leave it all on the field!'
    },
    passText: '100+ yards! ESPN highlights incoming. Heisman voters are watching.',
    failText: 'Tough loss, but your individual stats impressed.'
  },
  {
    id: 'col_game_2',
    era: 'COLLEGE',
    name: 'Rivalry Game',
    type: 'game',
    icon: '🔥',
    description: 'The biggest rivalry in college football',
    color: '#3b82f6',
    teamColor: '#1d4ed8',
    uniform: 'college',
    obstacleTypes: ['defender_medium', 'defender_fast', 'defender_blitz'],
    targetYards: 180,
    timeLimit: 40,
    lanes: 5,
    defenderCount: 8,
    difficulty: 1.5,
    starThresholds: [110, 155, 180],
    isBig: true,
    cutscene: {
      icon: '🔥',
      title: 'THE RIVALRY GAME',
      body: "It's THE game of the year. The governor is watching. Your cross-town rival has trash-talked all week. Silence the noise with your feet!"
    },
    passText: "DOMINANT PERFORMANCE! You're the talk of the nation.",
    failText: 'They got the best of you today. Remember this feeling.'
  },
  // BOWL GAME
  {
    id: 'bowl_practice',
    era: 'BOWL PREP',
    name: 'Bowl Week Practice',
    type: 'practice',
    icon: '🏟️',
    description: 'Final preparations for the big game',
    color: '#f59e0b',
    teamColor: '#d97706',
    uniform: 'college',
    obstacleTypes: ['defender_fast', 'defender_blitz'],
    targetYards: 160,
    timeLimit: 35,
    lanes: 5,
    defenderCount: 7,
    difficulty: 1.6,
    starThresholds: [100, 135, 160],
    cutscene: {
      icon: '🏟️',
      title: 'BOWL WEEK!',
      body: "It's bowl week in a warm city. Media day, fancy hotel, all eyes on the game. One last practice to sharpen your edge before the biggest game of your life!"
    },
    passText: "Sharpest you've ever looked. Bowl ready!",
    failText: "Shake it off — the game is what matters."
  },
  {
    id: 'bowl_game',
    era: 'BOWL GAME',
    name: '🏆 THE BOWL GAME',
    type: 'bowl',
    icon: '🏆',
    description: 'The national championship. Your moment.',
    color: '#f59e0b',
    teamColor: '#d97706',
    uniform: 'college',
    obstacleTypes: ['defender_fast', 'defender_blitz', 'defender_blitz'],
    targetYards: 200,
    timeLimit: 45,
    lanes: 5,
    defenderCount: 9,
    difficulty: 1.8,
    starThresholds: [130, 170, 200],
    isBig: true,
    isBowl: true,
    cutscene: {
      icon: '🏆',
      title: 'THE NATIONAL CHAMPIONSHIP',
      body: "This is it. The moment you've dreamed of since you were a kid throwing a ball in the backyard. One hundred million viewers. One game. Be legendary."
    },
    passText: 'BOWL CHAMPION! HALL OF FAME CAREER AWAITS!',
    failText: "You gave everything. The sport doesn't forget your name."
  }
];

export const UPGRADES = [
  { id: 'speed', name: 'Speed Burst', icon: '⚡', desc: 'Sprint recharges 20% faster', stat: 'sprintRegen', delta: 0.2, cost: 2, color: '#f59e0b' },
  { id: 'agility', name: 'Agility', icon: '🌀', desc: 'Move 15% faster side to side', stat: 'lateralSpeed', delta: 0.15, cost: 2, color: '#3b82f6' },
  { id: 'power', name: 'Power Back', icon: '💪', desc: 'Break one tackle per run', stat: 'breakTackle', delta: 1, cost: 3, color: '#ef4444' },
  { id: 'vision', name: 'Field Vision', icon: '👁️', desc: 'Defenders slow by 10%', stat: 'defenderSlow', delta: 0.1, cost: 3, color: '#8b5cf6' },
  { id: 'endurance', name: 'Endurance', icon: '❤️', desc: 'Start with +1 health point', stat: 'maxHealth', delta: 1, cost: 4, color: '#22c55e' },
  { id: 'elusiveness', name: 'Elusiveness', icon: '👻', desc: 'Hitbox 10% smaller', stat: 'hitboxShrink', delta: 0.1, cost: 3, color: '#06b6d4' },
  { id: 'stiffarm', name: 'Stiff Arm', icon: '🦾', desc: 'Stun nearby defenders', stat: 'stiffArm', delta: 1, cost: 4, color: '#f97316' },
  { id: 'cutback', name: 'Cutback King', icon: '🔪', desc: 'Lane switch costs no speed', stat: 'freeLane', delta: 1, cost: 2, color: '#ec4899' },
];

export const STAT_COLORS = {
  sprintRegen: '#f59e0b',
  lateralSpeed: '#3b82f6',
  breakTackle: '#ef4444',
  defenderSlow: '#8b5cf6',
  maxHealth: '#22c55e',
  hitboxShrink: '#06b6d4',
  stiffArm: '#f97316',
  freeLane: '#ec4899',
};
