const CACHE_NAME = 'Armor_Runner_21-v1';
const assets = [
  '/',
  'index.html',
  'sw.js',
  'manifest.json',
  'icon_192.jpg',
  'assets/runner/hs1.gif',
  'assets/runner/hs_invincible.gif',
  'assets/runner/hurdle1.gif',
  'assets/runner/pro_tuck1.gif',
  'assets/runner/hurdle_pro.gif',
  'assets/runner/down.png',
  'assets/defenders/d1.png',
  'assets/defenders/d2.jpeg',
  'assets/defenders/d3.png',
  'assets/defenders/d4.jpeg',
  'assets/powerups/powerups.png',
  'assets/items/item.png',
  'assets/backdrops/1.jpeg',
  'assets/backdrops/2.jpeg',
  'assets/backdrops/3.jpeg',
  'assets/backdrops/4.jpeg',
  'assets/backdrops/5.jpeg',
  'assets/backdrops/6.jpeg',
  'assets/backdrops/7.jpeg',
  'assets/backdrops/8.jpeg',
  'assets/endzones/endzone0.png',
  'assets/endzones/endzone1.png',
  'assets/endzones/endzone2.png',
  'assets/endzones/endzone3.png',
  'assets/endzones/endzone4.png',
  'assets/endzones/endzone5.png',
  'assets/endzones/endzone6.png',
  'assets/endzones/endzone7.png',
  'assets/grass/grass0.png',
  'assets/grass/grass1.png',
  'assets/grass/grass2.png',
  'assets/grass/grass3.png',
  'assets/grass/grass4.png',
  'assets/grass/grass5.png',
  'assets/grass/grass6.png',
  'assets/grass/grass7.png',
  'assets/grass/grass8.png'
];

self.addEventListener('install', e => e.waitUntil(caches.open(CACHE_NAME).then(c => c.addAll(assets))));
self.addEventListener('fetch', e => e.respondWith(caches.match(e.request).then(res => res || fetch(e.request))));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))))));
